include: ./sourcegraph-base.yaml

contents:
  packages:
    # Prometheus packages
    - prometheus-gcp@sourcegraph

paths:
  - path: /prometheus
    type: directory
    uid: 100
    gid: 101
    permissions: 0o755

work-dir: /prometheus
