include: ./sourcegraph-base.yaml

contents:
  packages:
    # Included by existing SG base image
    - tini
    - mailcap

    # Prometheus packages
    - prometheus
    - prometheus-alertmanager

paths:
  - path: /prometheus
    type: directory
    uid: 100
    gid: 101
    permissions: 0o755
  - path: /alertmanager
    type: directory
    uid: 100
    gid: 101
    permissions: 0o755

work-dir: /prometheus

# MANUAL REBUILD: Mon  7 Aug 2023 10:11:24 BST
