include: ./sourcegraph-base.yaml

contents:
  packages:
    # Prometheus packages
    - prometheus-gcp@sourcegraph
    - prometheus-alertmanager

paths:
  - path: /prometheus
    type: directory
    uid: 100
    gid: 101
    permissions: 0o755
  - path: /alertmanager
    type: directory
    uid: 100
    gid: 101
    permissions: 0o755

work-dir: /prometheus

# MANUAL REBUILD: Thu Aug 10 16:03:20 BST 2023
