apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sg-executor-multiqueue-role-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: sg-executor-service-account
    namespace: default
roleRef:
  kind: Role
  name: sg-executor-multiqueue-role
  apiGroup: rbac.authorization.k8s.io
