repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/keith/pre-commit-buildifier
    rev: 5.0.1
    hooks:
      - id: buildifier
      - id: buildifier-lint
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.9.0
    hooks:
    - id: shellcheck
  - repo: https://github.com/pecigonzalo/pre-commit-shfmt
    rev: 069d7b3826f1c1ab00ef37260dae39bafeee131f
    hooks:
      - id: shell-fmt-docker
  - repo: local
    hooks:
    - id: prettier
      name: prettier
      description: ''
      entry: pnpm prettier --write --list-different --ignore-unknown --config prettier.config.js
      language: system
      'types': [text]
      files: \.(js|json|ts|tsx|graphql|md|scss)
      args: []
      require_serial: false
