namespaces:
  - name: BATCH_CHANGES
    actions:
      - name: READ
      - name: WRITE
  - name: OWNERSHIP
    actions:
      - name: ASSIGN
        excludeFromUserRole: true
  - name: REPO_METADATA
    actions:
      - name: WRITE
