# Loosely based on the cadvisor Dockerfile, without support for ipmctl
#   https://github.com/google/cadvisor/blob/master/deploy/Dockerfile
package:
  name: cadvisor
   # libpfm version may also need updating - check cadvisor Dockerfile
  version: 0.47.2
  epoch: 1
  description: "Analyzes resource usage and performance characteristics of running containers"
  target-architecture:
    - x86_64
  copyright:
    - paths:
      - "*"
      attestation: 'Copyright 2014 The cAdvisor Authors'
      license: 'Apache License 2.0'
  dependencies:
    runtime:
      - device-mapper
      - findutils
      - ndctl
      - thin-provisioning-tools

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - wolfi-base
      - busybox
      - ca-certificates-bundle
      - build-base
      - cmake
      - device-mapper
      - findutils
      - git
      - go
      - linux-headers
      - ndctl-dev
      - thin-provisioning-tools

pipeline:
  # Fetch and build libpfm
  - uses: fetch
    with:
      uri: https://sourceforge.net/projects/perfmon2/files/libpfm4/libpfm-4.11.0.tar.gz
      expected-sha256: 5da5f8872bde14b3634c9688d980f68bda28b510268723cc12973eedbab9fecc
      strip-components: 0
  - runs: |
      pwd
      export DBG="-g -Wall"
      make -e -C libpfm-4.11.0
      make install -C libpfm-4.11.0

# Fetch cadvisor
  - uses: fetch
    with:
      uri: https://github.com/google/cadvisor/releases/download/v0.47.2/cadvisor-v0.47.2-linux-amd64
      extract: false
      expected-sha256: 30602f675e9bcd39b0d4cd4bd9e83c0849dd4bb3a60a0544b9f2a6451a3facfe
      strip-components: 0

  # Package libpfm and cadvisor
  - runs: |
      mkdir -p ${{targets.destdir}}/usr/bin/
      mkdir -p ${{targets.destdir}}/usr/local/lib/
      cp /home/build/cadvisor-v0.47.2-linux-amd64 ${{targets.destdir}}/usr/bin/cadvisor
      cp /usr/local/lib/libpfm.so* ${{targets.destdir}}/usr/local/lib/
      chmod +x ${{targets.destdir}}/usr/bin/cadvisor

