# Temporary repackage of chainguard package to work around APKINDEX signing issue
package:
  name: grafana
  version: 7.5.25
  epoch: 0
  description: "Open source, feature rich metrics dashboard and graph ed"
  target-architecture:
    - x86_64
  copyright:
    - paths:
      - "*"
      attestation: ''
      license: 'Apache License 2.0'
  dependencies:
    runtime:

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - wolfi-base
      - busybox
      - ca-certificates-bundle

pipeline:
  - runs: |
      cd grafana
      tar zxvf grafana-7.5.25-r0.apk.original
      ls -al
  - runs: |
      mkdir -p ${{targets.destdir}}
      ls -al ${{targets.destdir}}
      cp -r $HOME/grafana/etc ${{targets.destdir}}/etc
      cp -r $HOME/grafana/opt ${{targets.destdir}}/opt
      cp -r $HOME/grafana/usr ${{targets.destdir}}/usr
      cp -r $HOME/grafana/var ${{targets.destdir}}/var
      ls -al ${{targets.destdir}}
