name: File Size Checker

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check-size:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Check for large files
      run: |
        # Fetch the target branch to compare
        git fetch origin ${{ github.base_ref }}:${{ github.base_ref }}

        # Check for added or modified files larger than 1MB
        # changed_files=$(git diff --name-only --diff-filter=AM --merge-base ${{ github.base_ref }})
        changed_files=$(git diff --name-only --diff-filter=A --merge-base ${{ github.base_ref }})
        while read file; do
          old_size=$(git ls-tree -r ${{ github.base_ref }} -l "$file" | cut -f 4 -w)
          old_size=${old_size:-0}
          new_size=$(git ls-tree -r HEAD -l "$file" | cut -f 4 -w)
          if [ "$new_size" -gt "1000000" ] && [ "$old_size" -le "1000000" ]; then
            echo "$file exceeds 1MB"
            exit 1
          fi
        done <<< "$changed_files"
