name: File Size Checker

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check-size:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Check for large files
      run: |
        # Fetch the target branch to compare
        git fetch origin ${{ github.base_ref }}:${{ github.base_ref }}

        # Check for added or modified files larger than 1MB
        files=$(git diff --name-only --diff-filter=AM ${{ github.base_ref }} | while read file; do
          if [ $(git ls-tree -r HEAD "$file" | cut -f 5 -d ' ' | awk '{ if ($1 >= 1048576) print $1 }') ]; then
            echo "$file exceeds 1MB"
          fi
        done)

        if [[ ! -z "$files" ]]; then
          echo "$files"
          exit 1
        fi

