name: universal-ctags

on:
  push:
    paths:
    - 'dev/nix/ctags.nix'
  workflow_dispatch:

jobs:
  lints:
    name: Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4
      - name: Run `nix build`
        run: nix build -f dev/nix/ctags.nix
