name: universal-ctags

on:
  push:
    paths:
    - 'dev/nix/ctags.nix'
  workflow_dispatch:

jobs:
  x86_64-darwin:
    name: Build ctags
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4
      - id: auth
        name: '🔓 Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      - id: nix-build
        name: Run `nix build`
        run: |
          nix build .#ctags
          codesign --force -s - ./result/bin/ctags-*

      - id: 'upload-file'
        uses: 'google-github-actions/upload-cloud-storage@v1'
        with:
          path: './result/bin/'
          destination: 'universal_ctags/x86_64-darwin/'
          glob: 'ctags-*'
  aarch64-darwin:
    name: Build ctags
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4
      - id: auth
        name: '🔓 Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      - id: nix-build
        name: Run `nix build`
        run: |
          nix build .#ctags-aarch64-darwin
          codesign --force -vvvv -s - ./result/bin/ctags-*
      - id: 'upload-file'
        uses: 'google-github-actions/upload-cloud-storage@v1'
        with:
          path: './result/bin/'
          destination: 'universal_ctags/aarch64-darwin'
          glob: 'ctags-*'
  x86_64-linux:
    name: Build ctags
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4
      - id: auth
        name: '🔓 Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      - id: nix-build
        name: Run `nix build`
        run: |
          nix build .#ctags
      - id: 'upload-file'
        uses: 'google-github-actions/upload-cloud-storage@v1'
        with:
          path: './result/bin/'
          destination: 'universal_ctags/x86_64-linux'
          glob: 'ctags-*'
